### ISSUE TITLE
[Feature Request] Add template filter hook

### ISSUE THREAD

**Issue by urosevic** [urosevic/youtube-channel#1]
In cases where more detailed layout adjustments are needed, filter/action hooks for modifying the html output would be a good idea.

In our case we’d like to use our own css grid to layout the videos and modify the html structure as such (for title and description as well).

So please think about possibilities of themeing/filtering the html output.

**source:** https://wordpress.org/support/topic/feature-request-add-template-filter-hook/

**Comment by urosevic** [comment]
Initial filter hook `ytc_print_video` has been implemented in commit https://github.com/urosevic/youtube-channel/commit/d1d83b325e8c275410e4512b2bf2b8d1be424ca7

Four parameters are provided:
* `video_content` - HTML of original video block
* `item` - YouTube video object which contains:
  * `snippet->publishedAt` - date of publishing YouTube video
  * `shippet->title` - YouTube video title
  * `shippet->description` - YouTube video description
  * `snippet->resourceId->videoId` -> YouTube video ID
* `instance` - Current YouTUbe Channel Block parameters, including global settings:
  * `vanity`
  * `channel`
  * `username`
  * `playlist`
  * `resource`
  * `cache`
  * `fetch`
  * `num`
  * `privacy`
  * `ratio`
  * `width`
  * `responsive`
  * `display`
  * `themelight`
  * `fullscreen`
  * `controls`
  * `autoplay`
  * `autoplay_mute`
  * `norel`
  * `playsinline`
  * `showtitle`
  * `titletag`
  * `showdesc`
  * `desclen`
  * `modestbranding`
  * `hideanno`
  * `hideinfo`
  * `goto_txt`
  * `popup_goto`
  * `link_to`
  * `tinymce`
  * `nolightbox`
  * `apikey`
  * `thumb_quality`
  * `timeout`
  * `random`
  * `no_thumb_title`
  * `class`
  * `target`
* `y` - order number of video (`1` for first, `2` for second, etc)

Example:
```add_filter( 'ytc_print_video', 'customized_ytc_print_video', 10, 4 );
function customized_ytc_print_video( $video_block, $item, $instance, $y ) {
  // Do whatever you wish to do
  // ...
  return $video_block;
}```

**Comment by zitrusblau** [comment]
nice! 👍
