### ISSUE TITLE
Youtube channel widget Thumbnail

### ISSUE THREAD

**Issue by naqvispace** [urosevic/youtube-channel#3]
Hi,  I want a custom youtube video thumbnail image,  how i can do it??

**Comment by urosevic** [comment]
Hi @naqvispace,

Unfortunately, thumbnails in YouTube Channel are pulled from video on YouTube. So the only way to achieve what you asked for is to set a custom video cover for video on YouTube, and the YouTube Channel plugin will pull that cover image on the website.

Alternatively, you could override default YouTube thumbnail by setting your custom image for `background-image` through CSS by targeting span with id selector `yt_VIDEOID` (eg. `ytc_wOqkfkNhOUE`, but with ID of your video). Something like this:

```
.ytc_video_container span#ytc_wOqkfkNhOUE {
    background-image: url("url-of-your-image") !important;
}
```

Thank you for understanding,
Aleksandar

**Comment by naqvispace** [comment]
Thanks, I fixed it by doing custom thumbnail.
